[package]
name = "top-logs"
version = "0.1.0"
authors = ["Daniel Mikusa <dmikusa@pivotal.io>"]
edition = "2018"
description = "Tops logs is a tool which can be used to parse through access logs to understand usage trends and hunt for problems"
repository = "https://github.com/dmikusa-pivotal/top-logs"
readme = "README.md"
license = "Apache-2.0"
keywords = ["access", "logs", "parse"]
categories = ["parsing", "parser-implementations"]

[dependencies]
access_log_parser = "^0.1"
chrono = "^0.4"
http = "^0.1"
defaultmap = "^0.3"
prettytable-rs = "^0.8"
clap = "^2"